### ISSUE TITLE
GW2PAO crashed after resuming from sleep mode

### ISSUE THREAD

**Issue by StevenLiekens** [SamHurne/gw2pao#1] opened 2014-09-17 17:20 UTC
I'm not yet sure what caused it exactly. I resumed my laptop, and that's when the program crashed. The offending code is on line 335 of the WvWController: https://github.com/SamHurne/gw2pao/blob/master/GW2PAO/Controllers/WvWController.cs#L335

The exception said that the `latestObjectivesData` collection did not contain any matching elements.

**Comment by SamHurne** [comment] 2015-07-02 23:41
I have not been able to reproduce this for several months (pretty much since I switched to using Prism for bootstrapping the application). I'm going to go ahead and close this for now. If it reappears, we can reopen the issue.

**Closed by SamHurne** 2015-07-02 23:41 UTC
Labels: Issue

**Comment by mwrich4** [comment] 2016-03-30 23:32
FWIW, I see a crash message each time I resume from sleep using the latest build (3.5.5744.31293).  I'm running windows 7 Pro.  

It's a minor trouble, since I have to launch GW2 anyway.  Mentioning it only because I see this on the issue list.
