### ISSUE TITLE
Teamspeak window causes fatal error on close

### ISSUE THREAD

**Issue by reecebedding** [SamHurne/gw2pao#18] opened 2015-08-31 13:54 UTC
The team speak window causes fatal error on close, causing entire PAO process to end.
Here are the most recent log entries. http://pastebin.com/iwsrbaaX

**Comment by SamHurne** [comment] 2015-08-31 15:03
Confirmed - I have seen several crash reports for this issue. The problem is related to a partial-cleanup when disconnecting from the TS client query plugin. The fix has already been implemented and will be included in the next release.

**Comment by SamHurne** [comment] 2015-08-31 15:06
Didn't mean to actually close quite yet...

**Comment by reecebedding** [comment] 2015-08-31 20:37
Yea your right, i just compiled it from here, rather than using the installer and it works fine.

**Closed** 2015-09-19 22:47 UTC
Labels: Fixed - Pending Release, Issue
